baseURL = "https://wgbbiao.github.io/wgb237/"
domainVerification = "hahahaahah"
languageCode = "en-us"
theme = "bleak"
title = "我的第一站"
[Params]
cover = "about/"
instagram = "123"
mainsections = ["post"]
subtitle = "我的第一次测试"
[[menu.main]]
identifier = "about"
name = "about hugo"
pre = "<i class='fa fa-heart'></i>"
url = "/about/"
weight = -110
[[menu.main]]
name = "getting started"
post = "<span class='alert'>New!</span>"
pre = "<i class='fa fa-road'></i>"
url = "/test1/"
weight = -100
[[menu.subscription]]
title = "ddd"
[params]
cover = "about/"
instagram = "123"
mainsections = ["post"]
subtitle = "我的第二次测试"
