---
new_page_extension: md
auto_deploy: true
admin_path: backend
webhook_url: 
sections:
- type: directory
  path: content/test
  label: TEST2
  create: all
  match: "**/*"
  templates:
  - f97164e9-8101-413c-aa62-c4fc1756a581
  - aa4
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
  templates:
  - f97164e9-8101-413c-aa62-c4fc1756a581
- type: heading
  label: 单面
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - f97164e9-8101-413c-aa62-c4fc1756a581
- type: document
  path: content/TESTall.md
  label: TESTall
- type: directory
  path: tv
  label: 电视
  create: all
  match: "**/*"
  templates:
  - f97164e9-8101-413c-aa62-c4fc1756a581
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.48'
